### ISSUE TITLE
Case: remind me to do something in 15 minutes

### ISSUE THREAD

**Issue by heikohaller** [lacona/lacona.github.io#1]
Feature request
This does not work yet in the online demo: 
"remind me to test lacona in 15 minutes" (meaning 15 minutes from now).

**Comment by brandonhorst** [comment]
Good find! I'll get that fixed up right away.

**Comment by brandonhorst** [comment]
Should be fixed with https://github.com/lacona/www.lacona.io/commit/0a72dba3782c8eb7f55ddbf668e851e4e6b04c53. I also added "remind me to test Lacona 13 minutes from now." Thanks for the report!

![screen shot 2015-07-30 at 9 38 36 pm](https://cloud.githubusercontent.com/assets/1938545/8999089/6f8965a8-3703-11e5-84e2-c50f220f73cd.png)
